<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Controller;

use MU\TransportModule\Controller\Base\AbstractTableController;

use RuntimeException;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Zikula\ThemeModule\Engine\Annotation\Theme;
use MU\TransportModule\Entity\TableEntity;
use PDO;

/**
 * Table controller class providing navigation and interaction functionality.
 */
class TableController extends AbstractTableController
{
    /**
     * @inheritDoc
     *
     * @Route("/admin/tables",
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminIndexAction(Request $request)
    {
        return parent::adminIndexAction($request);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/tables",
     *        methods = {"GET"}
     * )
     */
    public function indexAction(Request $request)
    {
        return parent::indexAction($request);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/tables/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminViewAction(Request $request, $sort, $sortdir, $pos, $num)
    {
        return parent::adminViewAction($request, $sort, $sortdir, $pos, $num);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/tables/view/{sort}/{sortdir}/{pos}/{num}.{_format}",
     *        requirements = {"sortdir" = "asc|desc|ASC|DESC", "pos" = "\d+", "num" = "\d+", "_format" = "html"},
     *        defaults = {"sort" = "", "sortdir" = "asc", "pos" = 1, "num" = 10, "_format" = "html"},
     *        methods = {"GET"}
     * )
     */
    public function viewAction(Request $request, $sort, $sortdir, $pos, $num)
    {
        return parent::viewAction($request, $sort, $sortdir, $pos, $num);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/table/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function adminEditAction(Request $request)
    {
        return parent::adminEditAction($request);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/table/edit/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"id" = "0", "_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     */
    public function editAction(Request $request)
    {
        return parent::editAction($request);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/table/delete/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function adminDeleteAction(Request $request, $id)
    {
        return parent::adminDeleteAction($request, $id);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/table/delete/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET", "POST"}
     * )
     */
    public function deleteAction(Request $request, $id)
    {
        return parent::deleteAction($request, $id);
    }
    
    /**
     * @inheritDoc
     * @Route("/admin/tables/getTables",
     *        methods = {"GET", "POST"}
     * )
     * @Theme("admin")
     */
    public function adminGetTablesAction(Request $request)
    {
        return parent::adminGetTablesAction($request);
    }
    
    /**
     * @inheritDoc
     * @Route("/tables/getTables",
     *        methods = {"GET", "POST"}
     * )
     */
    public function getTablesAction(Request $request)
    {
        return parent::getTablesAction($request);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/admin/table/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     * @Theme("admin")
     */
    public function adminDisplayAction(Request $request, $id)
    {
        return parent::adminDisplayAction($request, $id);
    }
    
    /**
     * @inheritDoc
     *
     * @Route("/table/{id}.{_format}",
     *        requirements = {"id" = "\d+", "_format" = "html"},
     *        defaults = {"_format" = "html"},
     *        methods = {"GET"}
     * )
     */
    public function displayAction(Request $request, $id)
    {
        return parent::displayAction($request, $id);
    }
    
    /**
     * @inheritDoc
     * @Route("/admin/tables/handleSelectedEntries",
     *        methods = {"POST"}
     * )
     * @Theme("admin")
     */
    public function adminHandleSelectedEntriesAction(Request $request)
    {
        return parent::adminHandleSelectedEntriesAction($request);
    }
    
    /**
     * This method includes the common implementation code for adminGetTables() and getTables().
     */
    protected function getTablesInternal(Request $request, $isAdmin = false)
    {
    	// parameter specifying which type of objects we are treating
    	$objectType = 'table';
    	$permLevel = $isAdmin ? ACCESS_ADMIN : ACCESS_OVERVIEW;
    	if (!$this->hasPermission('MUTransportModule:' . ucfirst($objectType) . ':', '::', $permLevel)) {
    		throw new AccessDeniedException();
    	}
    
    	$templateParameters = [
    			'routeArea' => $isAdmin ? 'admin' : ''
    	];
    	 
    	// we get two helpers
    	$controllerHelper = $this->get('mu_transport_module.controller_helper');
    	$modelHelper = $this->get('mu_transport_module.model_helper');
    	// we get the relevant database id
    	$databaseId = $controllerHelper->getParameter('database');
    	// we get a database repository
    	$databaseRepository = $modelHelper->getRepository('database');
    	// we get the database object
    	$database = $databaseRepository->findOneBy(array('id' => $databaseId));
    	$conn = new \PDO('mysql:dbname=' . $database['dbName'] . ';host=' . $database['host'], $database['dbUser'], $database['dbPassword']);
    	$result = $conn->query('SHOW TABLES');
    	while ($row = $result->fetch(PDO::FETCH_NUM)) {
    		$tableList[] = $row[0];
    	}
    
    	foreach ($tableList as $table) {
    		$newTable = new TableEntity();
    		$newTable->setName($table);
    		$newTable->setDatabase($database);
    		$newTable->setWorkflowState('approved');
    		$this->getDoctrine()->getManager()->persist($newTable);
    		$this->getDoctrine()->getManager()->flush();
    	}
    	$templateParameters['tables'] = $tableList;
    
    	// return template
    	return $this->render('@MUTransportModule/Table/getTables.html.twig', $templateParameters);
    }

    // feel free to add your own controller methods here
}
