<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Zikula\Core\Doctrine\EntityAccess;
use MU\TransportModule\Traits\StandardFieldsTrait;
use MU\TransportModule\Validator\Constraints as TransportAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for database entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractDatabaseEntity extends EntityAccess
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'database';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     *
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @TransportAssert\ListEntry(entityName="database", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $name
     */
    protected $name = '';
    
    /**
     * @ORM\Column(length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $dbName
     */
    protected $dbName = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $dbUser
     */
    protected $dbUser = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="255")
     * @var string $dbPassword
     */
    protected $dbPassword = '';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $host
     */
    protected $host = '';
    
    
    /**
     * Bidirectional - One database [database] has many tables [tables] (INVERSE SIDE).
     *
     * @ORM\OneToMany(targetEntity="MU\TransportModule\Entity\TableEntity", mappedBy="database")
     * @ORM\JoinTable(name="mu_transport_databasetables")
     * @var \MU\TransportModule\Entity\TableEntity[] $tables
     */
    protected $tables = null;
    
    
    /**
     * DatabaseEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
        $this->tables = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = $_objectType;
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * Sets the name.
     *
     * @param string $name
     *
     * @return void
     */
    public function setName($name)
    {
        if ($this->name !== $name) {
            $this->name = isset($name) ? $name : '';
        }
    }
    
    /**
     * Returns the db name.
     *
     * @return string
     */
    public function getDbName()
    {
        return $this->dbName;
    }
    
    /**
     * Sets the db name.
     *
     * @param string $dbName
     *
     * @return void
     */
    public function setDbName($dbName)
    {
        if ($this->dbName !== $dbName) {
            $this->dbName = isset($dbName) ? $dbName : '';
        }
    }
    
    /**
     * Returns the db user.
     *
     * @return string
     */
    public function getDbUser()
    {
        return $this->dbUser;
    }
    
    /**
     * Sets the db user.
     *
     * @param string $dbUser
     *
     * @return void
     */
    public function setDbUser($dbUser)
    {
        if ($this->dbUser !== $dbUser) {
            $this->dbUser = isset($dbUser) ? $dbUser : '';
        }
    }
    
    /**
     * Returns the db password.
     *
     * @return string
     */
    public function getDbPassword()
    {
        return $this->dbPassword;
    }
    
    /**
     * Sets the db password.
     *
     * @param string $dbPassword
     *
     * @return void
     */
    public function setDbPassword($dbPassword)
    {
        if ($this->dbPassword !== $dbPassword) {
            $this->dbPassword = isset($dbPassword) ? $dbPassword : '';
        }
    }
    
    /**
     * Returns the host.
     *
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }
    
    /**
     * Sets the host.
     *
     * @param string $host
     *
     * @return void
     */
    public function setHost($host)
    {
        if ($this->host !== $host) {
            $this->host = isset($host) ? $host : '';
        }
    }
    
    
    /**
     * Returns the tables.
     *
     * @return \MU\TransportModule\Entity\TableEntity[]
     */
    public function getTables()
    {
        return $this->tables;
    }
    
    /**
     * Sets the tables.
     *
     * @param \MU\TransportModule\Entity\TableEntity[] $tables
     *
     * @return void
     */
    public function setTables($tables)
    {
        foreach ($this->tables as $tableSingle) {
            $this->removeTables($tableSingle);
        }
        foreach ($tables as $tableSingle) {
            $this->addTables($tableSingle);
        }
    }
    
    /**
     * Adds an instance of \MU\TransportModule\Entity\TableEntity to the list of tables.
     *
     * @param \MU\TransportModule\Entity\TableEntity $table The instance to be added to the collection
     *
     * @return void
     */
    public function addTables(\MU\TransportModule\Entity\TableEntity $table)
    {
        $this->tables->add($table);
        $table->setDatabase($this);
    }
    
    /**
     * Removes an instance of \MU\TransportModule\Entity\TableEntity from the list of tables.
     *
     * @param \MU\TransportModule\Entity\TableEntity $table The instance to be removed from the collection
     *
     * @return void
     */
    public function removeTables(\MU\TransportModule\Entity\TableEntity $table)
    {
        $this->tables->removeElement($table);
        $table->setDatabase(null);
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array List of resulting arguments
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'mutransportmodule.ui_hooks.databases';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects Objects that are added to this array
     * 
     * @return array List of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = [])
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Database ' . $this->getKey() . ': ' . $this->getName();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
