<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Core\Doctrine\EntityAccess;
use MU\TransportModule\Traits\StandardFieldsTrait;
use MU\TransportModule\Validator\Constraints as TransportAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for table entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractTableEntity extends EntityAccess
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'table';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     *
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @TransportAssert\ListEntry(entityName="table", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $name
     */
    protected $name = '';
    
    /**
     * @ORM\Column(type="text", length=2000)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="2000")
     * @var text $description
     */
    protected $description = '';
    
    
    /**
     * Bidirectional - Many tables [tables] are linked by one database [database] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="MU\TransportModule\Entity\DatabaseEntity", inversedBy="tables")
     * @ORM\JoinTable(name="mu_transport_database")
     * @Assert\Type(type="MU\TransportModule\Entity\DatabaseEntity")
     * @var \MU\TransportModule\Entity\DatabaseEntity $database
     */
    protected $database;
    
    /**
     * Bidirectional - One table [table] has many fields [fields] (INVERSE SIDE).
     *
     * @ORM\OneToMany(targetEntity="MU\TransportModule\Entity\FieldEntity", mappedBy="table")
     * @ORM\JoinTable(name="mu_transport_tablefields")
     * @var \MU\TransportModule\Entity\FieldEntity[] $fields
     */
    protected $fields = null;
    
    
    /**
     * TableEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
        $this->fields = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = isset($_objectType) ? $_objectType : '';
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    
    /**
     * Sets the name.
     *
     * @param string $name
     *
     * @return void
     */
    public function setName($name)
    {
        if ($this->name !== $name) {
            $this->name = isset($name) ? $name : '';
        }
    }
    
    /**
     * Returns the description.
     *
     * @return text
     */
    public function getDescription()
    {
        return $this->description;
    }
    
    /**
     * Sets the description.
     *
     * @param text $description
     *
     * @return void
     */
    public function setDescription($description)
    {
        if ($this->description !== $description) {
            $this->description = isset($description) ? $description : '';
        }
    }
    
    
    /**
     * Returns the database.
     *
     * @return \MU\TransportModule\Entity\DatabaseEntity
     */
    public function getDatabase()
    {
        return $this->database;
    }
    
    /**
     * Sets the database.
     *
     * @param \MU\TransportModule\Entity\DatabaseEntity $database
     *
     * @return void
     */
    public function setDatabase($database = null)
    {
        $this->database = $database;
    }
    
    /**
     * Returns the fields.
     *
     * @return \MU\TransportModule\Entity\FieldEntity[]
     */
    public function getFields()
    {
        return $this->fields;
    }
    
    /**
     * Sets the fields.
     *
     * @param \MU\TransportModule\Entity\FieldEntity[] $fields
     *
     * @return void
     */
    public function setFields($fields)
    {
        foreach ($this->fields as $fieldSingle) {
            $this->removeFields($fieldSingle);
        }
        foreach ($fields as $fieldSingle) {
            $this->addFields($fieldSingle);
        }
    }
    
    /**
     * Adds an instance of \MU\TransportModule\Entity\FieldEntity to the list of fields.
     *
     * @param \MU\TransportModule\Entity\FieldEntity $field The instance to be added to the collection
     *
     * @return void
     */
    public function addFields(\MU\TransportModule\Entity\FieldEntity $field)
    {
        $this->fields->add($field);
        $field->setTable($this);
    }
    
    /**
     * Removes an instance of \MU\TransportModule\Entity\FieldEntity from the list of fields.
     *
     * @param \MU\TransportModule\Entity\FieldEntity $field The instance to be removed from the collection
     *
     * @return void
     */
    public function removeFields(\MU\TransportModule\Entity\FieldEntity $field)
    {
        $this->fields->removeElement($field);
        $field->setTable(null);
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array List of resulting arguments
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'mutransportmodule.ui_hooks.tables';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects Objects that are added to this array
     * 
     * @return array List of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = [])
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Table ' . $this->getKey() . ': ' . $this->getName();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    }
}
