<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Form\Type;

use MU\TransportModule\Form\Type\Base\AbstractFieldType;

/**
 * Field editing form type implementation class.
 */
class FieldType extends AbstractFieldType
{
    // feel free to extend the field editing form type class here
}
