<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Form\Type;

use MU\TransportModule\Form\Type\Base\AbstractFieldselectType;

/**
 * Database editing form type implementation class.
 */
class FieldselectType extends AbstractFieldselectType
{
    // feel free to extend the database editing form type class here
}
