<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\TransportModule\Entity\TableEntity;

/**
 * Event base class for filtering table processing.
 */
class AbstractFilterTableEvent extends Event
{
    /**
     * @var TableEntity Reference to treated entity instance.
     */
    protected $table;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterTableEvent constructor.
     *
     * @param TableEntity $table Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(TableEntity $table, array $entityChangeSet = [])
    {
        $this->table = $table;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return TableEntity
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
