<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule;

use MU\TransportModule\Base\AbstractTransportEvents;

/**
 * Events definition implementation class.
 */
class TransportEvents extends AbstractTransportEvents
{
    // feel free to extend the events definition here
}
