<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use MU\TransportModule\Entity\Factory\EntityFactory;


/**
 * Database selection form type base class.
 */
abstract class AbstractFieldselectType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var EntityFactory
     */
    protected $entityFactory;

    /**
     * DatabaseType constructor.
     *
     * @param TranslatorInterface $translator    Translator service instance
     * @param EntityFactory $entityFactory EntityFactory service instance
     */
    public function __construct(
        TranslatorInterface $translator,
        EntityFactory $entityFactory
    ) {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

   /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $this->addListViewsFields($builder, $options);

        $builder
            ->add('select', SubmitType::class, [
                'label' => $this->__('Select and go further'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', SubmitType::class, [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for list views fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListViewsFields(FormBuilderInterface $builder, array $options)
    {
    	$source = $this->controllerHelper->getParameter('source');
    	$fieldRepository = $this->entityFactory->getRepository('field');
    	$where = 'tbl.table = ' . $source;
    	$listEntries = $fieldRepository->selectWhere();
    	$choices = [];
    	$choiceAttributes = [];
    	foreach ($listEntries as $entry) {
    		$choices[$entry['name']] = $entry['id'];
    		$choiceAttributes[$entry['text']] = ['title' => $entry['title']];
    	}
    	// we get the target fields
    	$target = $this->controllerHelper->getParameter('target');
    	$listEntries2 = $fieldRepository->selectWhere();
    	$choices2 = [];
    	$choiceAttributes2 = [];
    	foreach ($listEntries2 as $entry) {
    		$choices2[$entry['name']] = $entry['id'];
    		$choiceAttributes2[$entry['text']] = ['title' => $entry['title']];
    	}

    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'mutransportmodule_transport';
    }
}
