<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Form\Type\Base;

use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\Translator\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use MU\TransportModule\Entity\Factory\EntityFactory;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;


/**
 * Database selection form type base class.
 */
abstract class AbstractFieldselectType extends AbstractType
{
    use TranslatorTrait;

    /**
     * @var EntityFactory
     */
    protected $entityFactory;
    
    /**
     * @var Request;
     */
    protected $request;

    /**
     * DatabaseType constructor.
     *
     * @param TranslatorInterface $translator    Translator service instance
     * @param EntityFactory $entityFactory EntityFactory service instance
     * @param RequestStack $request RequestStack instance
     */ 
    public function __construct(
        TranslatorInterface $translator,
        EntityFactory $entityFactory,
    	RequestStack $requestStack
    ) {
        $this->setTranslator($translator);
        $this->entityFactory = $entityFactory;
        $this->request = $requestStack->getCurrentRequest();
    }

    /**
     * Sets the translator.
     *
     * @param TranslatorInterface $translator Translator service instance
     */
    public function setTranslator(/*TranslatorInterface */$translator)
    {
        $this->translator = $translator;
    }

   /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    	$this->addListViewsFields($builder, $options);
        $builder
            ->add('select', SubmitType::class, [
                'label' => $this->__('Select and go further'),
                'icon' => 'fa-check',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
            ->add('cancel', SubmitType::class, [
                'label' => $this->__('Cancel'),
                'icon' => 'fa-times',
                'attr' => [
                    'class' => 'btn btn-default',
                    'formnovalidate' => 'formnovalidate'
                ]
            ])
        ;
    }

    /**
     * Adds fields for list views fields.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addListViewsFields(FormBuilderInterface $builder, array $options)
    {    	
    		$builder->add('fieldCombination', HiddenType::class, [
    				'data' => '0'
    		]);
    		$source = $this->request->query->getDigits('source');
    		$builder->add('source', HiddenType::class, [   		
    				'data' => $source
    		]);
    		$target = $this->request->query->getDigits('target');
    		$builder->add('target', HiddenType::class, [ 		
    				'data' => $target
    		]);

    }

    /**
     * @inheritDoc
     */
    public function getBlockPrefix()
    {
        return 'mutransportmodule_transport';
    }
    
}
