<?php
/**
 * Transport.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link https://ziku.la
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\TransportModule\Event;

use MU\TransportModule\Event\Base\AbstractFilterTableEvent;

/**
 * Event implementation class for filtering table processing.
 */
class FilterTableEvent extends AbstractFilterTableEvent
{
    // feel free to extend the event class here
}
